source 'https://git.oschina.net/oneonelayer/HXSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, ‘8.0’

target 'HeXunMaster' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'ReactiveCocoa', '2.5'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJExtension', '~> 3.0.11'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'MBProgressHUD'
    pod 'FMDB', '~> 2.6.2'
    pod 'YYCategories', '~> 1.0.3'
    pod 'Masonry', '~> 1.0.1'
    pod 'TTTAttributedLabel', '1.13.4'
    pod "RTRootNavigationController", :git => 'https://github.com/arcangelw/RTRootNavigationController.git'
    pod 'SDWebImage'
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
    pod 'HXDataAnalytics', '>= 2.3.0'
#    pod 'DTCoreText'
  # Pods for HeXunMaster

end
